"""created ricks and morties

Revision ID: 5f3199b90ae5
Revises: 
Create Date: 2020-12-05 22:58:01.619134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3199b90ae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Morty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Dim', sa.Text(), nullable=True),
    sa.Column('Rickless', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Dim', sa.Text(), nullable=True),
    sa.Column('Morty_id', sa.Integer(), nullable=True),
    sa.Column('On_the_council', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Morty_id'], ['Morty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rick')
    op.drop_table('Morty')
    # ### end Alembic commands ###
